import { Bungee } from "next/font/google";
import "./globals.css";

const bungee_init = Bungee({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bungee",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bungee_init.className}>{children}</body>
    </html>
  );
}
